// This file is normally generated by the FlutterFire CLI.
// Add FirebaseOptions here when you run `flutterfire configure`.
// For now keep as placeholder.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozfBHDWPc3cM_Ia2ew8CrWx_CtmQFafE',
    appId: '1:532660839767:web:a306927ba0ba164fa2ca12',
    messagingSenderId: '532660839767',
    projectId: 'drama-review-app',
    authDomain: 'drama-review-app.firebaseapp.com',
    storageBucket: 'drama-review-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUitEwg6KYAFmIQs83bK28N3qPwtw8O2g',
    appId: '1:532660839767:android:966f7f75f19cfc8fa2ca12',
    messagingSenderId: '532660839767',
    projectId: 'drama-review-app',
    storageBucket: 'drama-review-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP49N8-b88VgNNU5WntLcZXmu9QSolTEc',
    appId: '1:532660839767:ios:5ee1169d35b7ec22a2ca12',
    messagingSenderId: '532660839767',
    projectId: 'drama-review-app',
    storageBucket: 'drama-review-app.firebasestorage.app',
    iosBundleId: 'com.example.dramaReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP49N8-b88VgNNU5WntLcZXmu9QSolTEc',
    appId: '1:532660839767:ios:5ee1169d35b7ec22a2ca12',
    messagingSenderId: '532660839767',
    projectId: 'drama-review-app',
    storageBucket: 'drama-review-app.firebasestorage.app',
    iosBundleId: 'com.example.dramaReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAozfBHDWPc3cM_Ia2ew8CrWx_CtmQFafE',
    appId: '1:532660839767:web:c5d8446f01b1cb85a2ca12',
    messagingSenderId: '532660839767',
    projectId: 'drama-review-app',
    authDomain: 'drama-review-app.firebaseapp.com',
    storageBucket: 'drama-review-app.firebasestorage.app',
  );
}
